version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '08:00'
    timezone: US/Central
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: extract-loader
    versions:
    - "> 2.0.1"
  - dependency-name: memory-fs
    versions:
    - ">= 0.5.a, < 0.6"
  - dependency-name: nuxt-jsonld
    versions:
    - "> 1.4.3, < 1.5"
  - dependency-name: vue-jest
    versions:
    - ">= 5.0.a, < 5.1"
