---
version: 2
updates:
  - package-ecosystem: npm
    commit-message:
      prefix: 'chore: '
    directory: '/'
    schedule:
      interval: daily
      time: '08:00'
      timezone: US/Central
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
