---
name: CI
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - trunk
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
      - run: npm run terraform init
      - run: npm run terraform validate
  merge:
    needs: build
    if: ${{github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'}}
    runs-on: ubuntu-latest
    steps:
      - id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{secrets.GITHUB_TOKEN}}"
      - if: ${{steps.metadata.outputs.update-type == 'version-update:semver-major'}}
        run: gh run cancel ${{github.run_id}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - if: ${{steps.metadata.outputs.update-type != 'version-update:semver-major'}}
        run: gh pr merge --auto --squash ${{github.event.pull_request.html_url}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
