name: CI
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
    - name: Check out ${{ github.sha }}
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.node-version'
    - id: cache
      name: Fetch cached node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
        restore-keys: node-modules-${{ matrix.node-version }}-
    - name: Install npm packages
      run: npm ci
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Lint
      run: |
        bin/eslint
        bin/stylelint
    - run: |
        terraform init -backend=false
        terraform validate
      working-directory: infra
    - name: Build
      run: |
        bin/build
    - name: Test
      run: |
        bin/jest --collectCoverageFrom='{app,lambda}/**/*.js'
    - name: Report to Codecov.io
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bin/codecov --disable=gcov --file=coverage/coverage-final.json
    strategy:
      matrix:
        node-version: [14.x]
