name: CI
on:
  push:
    branches: [trunk]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.sha }}
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
      - id: cache
        name: Fetch cached node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node-modules-
      - name: Install npm packages
        run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run lint
      - run: |
          terraform init -backend=false
          terraform validate
        working-directory: infra
      - run: npm run build
      - run: npm run test
      - env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: npm run codecov
