name: CI
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
    - name: Checking out ${{ github.sha }}
      uses: actions/checkout@v2
    - name: Set up node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install npm packages
      run: npm ci
    - name: Lint
      run: |
        bin/eslint
        bin/stylelint
    - name: Build
      run: |
        bin/build
    - name: Test
      run: |
        bin/jest --collectCoverageFrom='{app,lambda}/**/*.js'
    - name: Report to Codecov.io
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bin/codecov --disable=gcov --file=coverage/coverage-final.json
    strategy:
      matrix:
        node-version: [14.x]
