name: nightly
on:
  schedule:
    - cron: '0 1 * * 2-6' # M-F 8pm CST
  workflow_dispatch:
jobs:
  analyze:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
    - name: Set up node
      uses: actions/setup-node@v2-beta
    - name: Install @lhci/cli
      run: npm i @lhci/cli
    - name: Collect
      env:
        LHCI_SERVER_BASE_URL: ${{ secrets.LHCI_SERVER_BASE_URL }}
        LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
      run: npx lhci collect
    - name: Upload
      env:
        LHCI_SERVER_BASE_URL: ${{ secrets.LHCI_SERVER_BASE_URL }}
        LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
      run: npx lhci upload
