name: nightly
on:
  schedule:
    - cron: '0 1 * * 2-6' # M-F 8pm CST
  workflow_dispatch:
jobs:
  analyze:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
    - name: Lighthouse
      env:
        LHCI_SERVER_BASE_URL: ${{ secrets.LHCI_SERVER_BASE_URL }}
        LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
      run: |
        bin/lhci collect
        bin/lhci upload
    strategy:
      matrix:
        node-version: [14.x]
