name: nightly
on:
  schedule:
    - cron: '0 1 * * 2-6'  # M-F 8pm CST
  workflow_dispatch:
jobs:
  analyze:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
      - run: rm package.json package-lock.json
      - run: npm i @lhci/cli
      - run: npx lhci collect
        env:
          LHCI_SERVER_BASE_URL: ${{ secrets.LHCI_SERVER_BASE_URL }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
      - run: bin/wake-up-lhci && sleep 15s
        env:
          LHCI_SERVER_BASE_URL: ${{ secrets.LHCI_SERVER_BASE_URL }}
      - run: npx lhci upload
        env:
          LHCI_SERVER_BASE_URL: ${{ secrets.LHCI_SERVER_BASE_URL }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
